### ISSUE TITLE
provide metric lib for relayers

### ISSUE THREAD

**Issue by akeyder** [aurora-is-near/relayer2-base#100]
make following metrics available for Prometheus to pull
- block height
- number of requests served
- resource usage?
- number of indexer errors?

configuration
- global enable/disable
- per metric enable/disable?
- port to server metrics

**Comment by JonathanLogan** [comment]
Metrics:
- block height consumed from NATS
- number of requests served
- number of indexer errors
- NO need for resource metrics.

Configuration:
- enable all metrics if metrics IP:Port is set 
- that's enough
